//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Shared
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Shared.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add plant.
        /// </summary>
        internal static string AddPlant {
            get {
                return ResourceManager.GetString("AddPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air temperature.
        /// </summary>
        internal static string AirTemperature {
            get {
                return ResourceManager.GetString("AirTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © UTM All Rights Reserved.
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current paramteres.
        /// </summary>
        internal static string CurrentParameters {
            get {
                return ResourceManager.GetString("CurrentParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Bot Ip.
        /// </summary>
        internal static string FarmBotIp {
            get {
                return ResourceManager.GetString("FarmBotIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irigations per day.
        /// </summary>
        internal static string IrigationsPerDay {
            get {
                return ResourceManager.GetString("IrigationsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        internal static string Liters {
            get {
                return ResourceManager.GetString("Liters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosity.
        /// </summary>
        internal static string Luminosity {
            get {
                return ResourceManager.GetString("Luminosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement unit.
        /// </summary>
        internal static string MeasurementUnit {
            get {
                return ResourceManager.GetString("MeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write some info about this plant.
        /// </summary>
        internal static string PlantInfoPlaceholder {
            get {
                return ResourceManager.GetString("PlantInfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant name.
        /// </summary>
        internal static string PlantName {
            get {
                return ResourceManager.GetString("PlantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant parameters.
        /// </summary>
        internal static string PlantParameters {
            get {
                return ResourceManager.GetString("PlantParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plants distance.
        /// </summary>
        internal static string PlantsDistance {
            get {
                return ResourceManager.GetString("PlantsDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plants list.
        /// </summary>
        internal static string PlantsList {
            get {
                return ResourceManager.GetString("PlantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total plants.
        /// </summary>
        internal static string PlantsListLabel {
            get {
                return ResourceManager.GetString("PlantsListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to start Farm Bot processes you should select a plant from added plants. If current process is not finished then it will be interrupted and new process will begin..
        /// </summary>
        internal static string PlantsListMessage {
            get {
                return ResourceManager.GetString("PlantsListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login:.
        /// </summary>
        internal static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video &amp; Controls.
        /// </summary>
        internal static string RealTimeVideo {
            get {
                return ResourceManager.GetString("RealTimeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use buttons to control camera.
        /// </summary>
        internal static string RealTimeVideoLabel {
            get {
                return ResourceManager.GetString("RealTimeVideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time.
        /// </summary>
        internal static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row distance.
        /// </summary>
        internal static string RowDistance {
            get {
                return ResourceManager.GetString("RowDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed depth.
        /// </summary>
        internal static string SeedDepth {
            get {
                return ResourceManager.GetString("SeedDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeding date.
        /// </summary>
        internal static string SeedingDate {
            get {
                return ResourceManager.GetString("SeedingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select plant.
        /// </summary>
        internal static string SelectPlant {
            get {
                return ResourceManager.GetString("SelectPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Ip.
        /// </summary>
        internal static string ServerIp {
            get {
                return ResourceManager.GetString("ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm bot settings.
        /// </summary>
        internal static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil humidity.
        /// </summary>
        internal static string SoilHumidity {
            get {
                return ResourceManager.GetString("SoilHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update parameters.
        /// </summary>
        internal static string UpdateParameters {
            get {
                return ResourceManager.GetString("UpdateParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water quantity.
        /// </summary>
        internal static string WaterQuantity {
            get {
                return ResourceManager.GetString("WaterQuantity", resourceCulture);
            }
        }
    }
}
